namespace ET
{
	public enum SceneType
	{
		Process = 0,
		Manager = 1,
		Realm = 2,
		Gate = 3,
		Http = 4,
		Location = 5,
		Map = 6,
		Fuben = 7,
		DBCache = 8,
		Chat = 9,
		EMail = 10,
		ReCharge = 11,
		Activity = 12,
		Rank = 13,
		PaiMai = 14,
		Center = 15,
		Team = 16,
		Friend = 17,
		GateMap = 18,
		Union = 19,
		Account = 20,
		LoginCenter = 21,
		Queue = 22,
		AccountCenter = 23,
		FubenCenter = 24,
		Battle = 25,
		Arena = 26,
		JiaYuan = 27,
		Popularize = 28,
		Solo = 29,
        LocalDungeon = 30,
		Happy = 31,
        RunRace = 32,
        Demon = 33,

        // 客户端Model层
        Client = 40,
		Zone = 41,
		Login = 42,
		Robot = 43,
		Current = 44,
	}
}